## Default configuration file for SimpleAbilities developed by sores ##
## Any time variables are based in seconds ##

abilities:
  switcher:
    enabled: true
    cooldown: 45
  cocaine:
    enabled: true
    cooldown: 30
    speed_level: 2
    speed_time: 5
  anti_build:
    enabled: true
    cooldown: 60
    time: 5
  smelting_shovel:
    enabled: true
  armor_swap:
    enabled: true
    cooldown: 60
    time: 3
    potion_effect: true
  lightning_rod:
    enabled: true
    cooldown: 45
  fall_protection:
    enabled: true
    cooldown: 60
  recall:
    enabled: true
    cooldown: 120
    range: 20
    potion_effect: true
